<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Signin Template · Bootstrap v5.0</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="./public/css/style.css">
</head>
<body class="text-center">
<header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3  bg-white bg-gradient border-bottom shadow-sm">
    <h1 class="h3 my-0 me-md-auto text-primary fw-normal">Tchat</h1>
    <nav class="my-2 my-md-0 me-md-3">
        <?php if(isset($_SESSION['user'])): ?>
        <a  aria-current="page" class="fs-4 text-decoration-none text-warning" href="#"><?= $_SESSION["user"]["nickname"] ?></a>
        <a  aria-current="page" class="fs-4 ms-3 text-decoration-none text-secondary" href="./account.php">Mon compte</a>
        <a  aria-current="page" class="fs-4 ms-3 text-decoration-none text-secondary" href="./index.php">Accueil</a>
        <a  href="./logout.php" class="fs-4 ms-3 text-decoration-none text-secondary">déconnexion</a>
        <?php else: ?>
        <a href="./register.php" class="nav-link text-uppercase font-weight-bold">Inscription</a>
        <a href="./login.php" class="nav-link text-uppercase font-weight-bold">Connexion</a>
        <?php endif; ?></ul>
    </nav>

</header>
<div class="container">
<?php require $template?>
</div>

</body>
</html>