<main class="form-signin">
    <form action="./login.php" method="post">
        <h1 class="h3 mb-3 fw-normal">Connexion</h1>
        <label for="email" class="visually-hidden">Email</label>
        <input type="text" id="email" name="email" class="form-control" placeholder="Email" required autofocus>
        <label for="password" class="visually-hidden">Mot de passe</label>
        <input type="password" id="password" name="password" class="form-control" placeholder="Mot de passe" required>

        <button class="w-100 btn btn-lg btn-primary" type="submit">connexion</button>

    </form>
</main>
